version: '3.4'

services:
  grpchttpservice.grpc:
    image: ${DOCKER_REGISTRY-}grpchttpservicegrpc
    build:
      context: .
      dockerfile: GrpcHttpService.Grpc/Dockerfile
    container_name: grpc-service
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__GrpcHttpServiceDB: "Server=sqlserver,1433;Database=GrpcDatabase;User Id=sa;Password=Admin123!;TrustServerCertificate=True"
    networks:
      - app-network

  grpchttpservice.http:
    build:
      context: .
      dockerfile: GrpcHttpService.Http/Dockerfile
    container_name: http-service
    ports:
      - "5000:5000"
    depends_on:
      - grpchttpservice.grpc
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      GRPC_SERVICE_URL: "http://grpc-service:8080"
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"                   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
